---
title: "Topic ideas"
author: "Team Octopi"
date: "10/11/19"
output: github_document
---

## Topic Ideas

### Idea #1
Trends in air quality over the years in the U.S.

More Specifically:
  Which states have the best/worst, how this has changed historically.
  What factors effect air quality, have the factors changed over time?
  
### Idea #2
International organ transplants: Which organs are the most requested or the most donated from each country across the world; whether the organs come from living or dead donors, how these trends have changed over decades

### Idea #3 
Statistics of Marijuana use at Duke University.
Analysis would include:
-Trends of the frequency of use across each year.
-Frequency of use based on pratt vs trinity students. 
-Trends in the methods of use (smoking, vaping, edibles, etc.). 
-Trends of use by greek organizations, selected living groups, and independent students.
-Frequency of use in correlation with gpa (ranged, not exact).

This data would be obtained via an anonymous Qualtrics survey.

### Idea #4

Statistics of adderall use at Duke University.
Analysis would include:
-Trends of the frequency of use across each year.
-Frequency of use based on pratt vs trinity students. 
-Trends in the use compared with high school. 
-Trends of use by different demographics.
-Frequency of those that are prescribed adderall.
-Trends in overall GPA
-Trends between majors/courses of study (pre-med, etc)
-Trends with use of other drugs/alcohol

This data would be obtained via an anonymous Qualtrics survey.

## Datasets

### Dataset #1
Historical Air Quality, corresponding to topic Idea #1
https://www.kaggle.com/epa/epa-historical-air-quality

### Dataset #2
INTERNATIONAL REGISTRY IN ORGAN DONATION AND TRANSPLANTATION, corresponding to topic Idea #2
http://www.irodat.org/